### ISSUE TITLE
Nginx doesn't restart on boot with xenial

### ISSUE THREAD

**Issue by ctaverne** [geerlingguy/ansible-role-nginx#151]
Hi

I don't understand. My ansible script has this issue since 2 days (with ubuntu xenial).
Nothing changed in my playbook.

Now it doesn't enable nginx service on startup.

I get:

> $ sudo systemctl status nginx
> ● nginx.service - A high performance web server and a reverse proxy server
>    Loaded: loaded (/lib/systemd/system/nginx.service; **disabled**; vendor preset: enabled)
> ...

I need to make the following change to make it enabled

> - name: Ensure nginx is started and enabled to start at boot.
>   service:
>     name: nginx
>     state: started
>     enabled: yes
>     **use: service**
>   become: yes

I was inspired by: https://github.com/geerlingguy/ansible-role-varnish/pull/65 and https://github.com/ansible/ansible/issues/22303

I just updated ansible from 2.5.0 to 2.5.1 and role to 2.5.1 too.
Nginx repository updated recently stable version to 1.14 too..

But it remains the same with old versions.. :( I can't come back to a working situation

**Comment by geerlingguy** [comment]
I haven't had an issue with this on any of my Xenial servers... do you know if you have any other strange configuration in place? E.g. are you overriding/removing systemd on these servers?

**Comment by ctaverne** [comment]
Hi,
First, thanks for your answer and for sharing this project.

Me too, I hadn't any issue until now

No, I'm using standard configuration. To be more specific, I'm using official AWS ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 (ami-1b791862)

**Comment by jportoles** [comment]
The official Xenial PPA for nginx 1.14 no longer auto enables the systemd job, I don't know if this is an issue with nginx itself or the PPA, but it's definitely not Ansible's fault.

**Comment by ctaverne** [comment]
@jportoles if nginx is no longer auto enabled in systemd, it doesn't explain why ansible can't manage this service anymore and can't enable it as previously?

**Comment by iainhouston** [comment]
Only after I do `sudo systemctl enable nginx` on the guest Ubuntu VM can I do `vagrant reload` to find nginx running on the rebooted VM.   

`geerlinggut/nginx` has:

    - name: Ensure nginx is started and enabled to start at boot.
      service: name=nginx state=started enabled=yes  

and this *should* translate to `systemctl enable nginx` shouldn't it? (ansible 2.5.2)

So what do you think is going on?

On Guest :  

-  Ubuntu latest 16.04 (`geerlingguy/ubuntu1604`)
-  nginx version: nginx/1.14.0

On host:  
-  Vagrant 2.1.0  
-  ansible 2.5.2

**Comment by ctaverne** [comment]
Hi,
I came back to 2.5.0 and 2.5.1 and got the same result. Maybe I lost something..

**Comment by thejchap** [comment]
Just upgraded Ansible to 2.5.4 and it looks like this is fixed

**Comment by danielcompton** [comment]
I have this issue too, though I got it in Ansible 2.5.3 but it still happened after rolling back to 2.4.3.0. I suspect there is something in a recent version of Nginx which has also changed here.

**Comment by danielcompton** [comment]
Hmm, I ran this against 2.5.4 and still had the same issues with nginx not being enabled.

**Comment by saeohioalpha** [comment]
Wondering if this is related. I recently updated my linode VM (UB16.04.5, 4.17.17-x86_64-linode116) to use nginx/1.15.3, openssl/1.1.1, and my systemd config started to not start on reboot. Systemd config was from the nginx.com website example. 

It was timing out on the prestart. I removed the prestart, and then it started timing out on the start. 

I adjusting the targets to make it start later in the process, still timed out. Then I added bin/sleep 15 to the prestart. Still timed out.

Sleep 30 also timed out, but allowed me to check the status and it looks like it times out after about 2 minutes of trying to start. 
 
![screen shot 2018-09-18 at 12 06 38 pm](https://user-images.githubusercontent.com/969559/45700816-842ff480-bb3b-11e8-8eee-c0b5e52aeed1.png)

When I manually run it by the cmd line it starts and starts in about 30s. Which seems long, but well within the 2 minute time out.

![screen shot 2018-09-18 at 12 10 01 pm](https://user-images.githubusercontent.com/969559/45700938-dcff8d00-bb3b-11e8-8250-e48177a221ef.png)

The previous version of nginx/openssl that was installed was nginx/1.13.12 openssl/1.1.0h

**Comment by zombieprocess** [comment]
It sorta looks like this was fixed in `ansible 2.6` in this PR, so maybe if people still have this issue, that is the resolution. https://github.com/ansible/ansible/pull/46245

**Comment by andrewvttran** [comment]
Having the same issue, and I'm running Ansible 2.7.1.

**Comment by geerlingguy** [comment]
Yeah; and in my quick testing with Drupal VM earlier today, it seemed to be working okay (I was testing a new base box which installed Nginx separately, then I rebooted and it was running correctly).

Closing this issue, feel free to reopen if you can reproduce the issue on newer versions of Ansible.
